### ISSUE TITLE
Support automatic loading of Integration Report

### ISSUE THREAD

**Issue by gentzel** [upsert/lutron-caseta-pro#19] opened 2019-01-23 00:42 UTC
Great component.  A critical  part of my HA setup as it lets me use Pico remotes for a myriad of tasks.  Thanks.

One enhancement I'd love to see is for the component to monitor a location (e.g. a fixed filename in an fixed directory) and automatically update the Integration Report if a file is either present or updated there.  This would allow, for example, exporting the Integration Report from the app to a Dropbox folder and then have to take no further action (other than possibly restarting HA) for it to be processed.

Once processed, the file could be renamed (e.g. add a ".processed" extension), deleted, or simply left in place and rely on the timestamp or an md5 to detect if it's updated.

There are likely some security considerations, so I might not enable this by default, but for my own configuration this would definitely simplify adding new devices.

**Comment by synthead** [comment] 2019-01-23 06:08
Duplicate of https://github.com/upsert/lutron-caseta-pro/issues/14

**Comment by gentzel** [comment] 2019-01-23 06:12
Certainly related to https://github.com/upsert/lutron-caseta-pro/issues/14, but I don't consider it a duplicate.  For example, what I'm proposing doesn't require ssh or other non-telnet access to the hub.

**Comment by upsert** [comment] 2019-01-23 12:25
The JSON integration report is loaded every time Home Assistant starts. If you make any changes to the file, they will be picked up when the system restarts. HA is designed to load all its components and platforms when it starts.

To update the report I recommend deleting the JSON file, restarting HA and then copy and paste from the Lutron app to the configurator that will appear in the front-end. It cuts out the middleman and having to copy the JSON through another service.

**Comment by gentzel** [comment] 2019-01-23 15:04
I guess I'm not expressing myself well.  It's the "copy from the app to the configurator" step that I'm proposing eliminating.

I can likely accomplish what I want with Dropbox + a symlink, just thought it would be simpler for direct support from the component.

**Comment by upsert** [comment] 2019-01-23 23:32
Ok, yeah this sounds like a job for [Folder sensor](https://www.home-assistant.io/components/sensor.folder/) and `homeassistant.restart` service. I would be hesitant to do an automation that restarts HA (infinite loops etc.), but it could work for your scenario.

**Closed as completed** 2019-01-26 19:40 UTC
