### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by dubhunter** [upsert/lutron-caseta-pro#48] opened 2020-03-08 06:25 UTC
I am having a very similar issue to https://github.com/upsert/lutron-caseta-pro/issues/39.

I have done all the config, and am seeing the following logs, but I do not see any devices added. I do see entities added, but no devices.

Please help, thanks!

```
2020-03-07 22:18:41 INFO (MainThread) [homeassistant.setup] Setting up lutron_caseta_pro
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading Integration Report /config/lutron_caseta_pro_10.x.x.x.json
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Setting up bridge using Integration Report /config/lutron_caseta_pro_10.x.x.x.json
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Patched device list [{'id': 2, 'name': 'Overhead Light', 'type': 'switch', 'area_name': 'Front Door'}]
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading platform sensor
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading platform switch
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading platform light
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading platform cover
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading platform scene
2020-03-07 22:18:41 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Loading platform fan
2020-03-07 22:18:41 INFO (MainThread) [homeassistant.setup] Setup of domain lutron_caseta_pro took 0.0 seconds.
2020-03-07 22:18:47 INFO (MainThread) [homeassistant.components.scene] Setting up scene.lutron_caseta_pro
2020-03-07 22:18:47 INFO (MainThread) [custom_components.lutron_caseta_pro] Opening connection to host 10.0.0.70
2020-03-07 22:18:47 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.lutron_caseta_pro
2020-03-07 22:18:47 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Starting Lutron component for host 10.0.0.70
2020-03-07 22:18:48 INFO (MainThread) [homeassistant.components.fan] Setting up fan.lutron_caseta_pro
2020-03-07 22:18:48 INFO (MainThread) [homeassistant.components.switch] Setting up switch.lutron_caseta_pro
2020-03-07 22:18:48 INFO (MainThread) [homeassistant.components.cover] Setting up cover.lutron_caseta_pro
2020-03-07 22:18:48 INFO (MainThread) [homeassistant.components.light] Setting up light.lutron_caseta_pro
2020-03-07 22:18:48 DEBUG (MainThread) [custom_components.lutron_caseta_pro.casetify] Sending query OUTPUT, integration 2, action 1
2020-03-07 22:18:49 DEBUG (MainThread) [custom_components.lutron_caseta_pro] Read value for host 10.x.x.x: OUTPUT 2 1 0.000000
2020-03-07 22:18:49 DEBUG (MainThread) [custom_components.lutron_caseta_pro.switch] Got switch OUTPUT value: OUTPUT 2 1 0.000000
```

**Comment by upsert** [comment] 2020-03-08 18:03
This component does not support the device registry if that is what you are after. You should still see the entity for your switch.

**Comment by dubhunter** [comment] 2020-03-09 17:20
Well I saw you had an open issue for that (that you opened). Hope it gets added!

**Comment by upsert** [comment] 2020-03-13 21:45
Marking as duplicate of #11.

**Closed as completed by upsert** 2020-03-13 21:45 UTC
Labels: enhancement
